feat:linked pages
vibebeta/vibebeta-site-policies pull request #12
Opened 2023-01-30 00:54 UTC by Sire6715

linked the pages using for loops and made the navbar heading display page title for every page.

2023-01-30 11:39 UTC, sammy-code98 approved these changes

2023-01-30 11:39 UTC, sammy-code98 commented on Copyright.md
> +permalink: /copyright/
great work uche.

i think the extra forward slash '/' in front should be removed

2023-01-30 11:52 UTC, copy-ninja1 requested changes
rename accountTerms to just terms and put it in a diffrent folder (terms/index.md)
put summary.md in it's own folder (summary/index.md) the same thing for other .md files

example
![Screenshot from 2023-01-30 12-51-37](https://user-images.githubusercontent.com/68874364/215469633-d2c01b41-c940-448e-8e6c-aa98e89aae11.png)

2023-01-30 22:18 UTC, Sire6715 commented
just finished making the changes to the url and the directories.
changed the default on load page to the "copyright infringement" page since its the first on the navigation menu.Awaiting your feedback/review, thank you.

2023-01-30 22:55 UTC, sammy-code98 approved these changes
Great work @Sire6715

2023-01-31 12:49 UTC, copy-ninja1 approved these changes

2023-01-31 12:49 UTC, merged