first commit
vibebeta/vibebeta-site-policies pull request #2
Opened 2022-12-30 15:49 UTC by Sire6715

Installed jekyll.

2022-12-30 20:57 UTC, sammy-code98 approved these changes

2022-12-30 21:20 UTC, sammy-code98 requested changes

2022-12-30 21:20 UTC, sammy-code98 commented on vibebeta-site-policies/_config.yml
> +title: Your awesome title
update title to  vibesbeta-site-policies

2022-12-30 21:20 UTC, sammy-code98 commented on vibebeta-site-policies/_config.yml
> +description: >- # this means to ignore newlines until "baseurl:"
update description as well, @copy-ninja1  please provide a better description text

2023-01-01 19:51 UTC, copy-ninja1 approved these changes

2023-01-03 13:05 UTC, sammy-code98 approved these changes

2023-01-03 13:05 UTC, merged